import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import { Plus_Jakarta_Sans, Inter } from 'next/font/google';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin', 'latin-ext'], // LATIN-EXT este obligatoriu pentru română (ș, ț, ă)
  weight: ['400', '500', '600', '700', '800'], // Alege greutățile de care ai nevoie
  variable: '--font-plus-jakarta', // Numele variabilei CSS
});

const inter = Inter({
  subsets: ['latin', 'latin-ext'],
  variable: '--font-inter', // Variabila pentru paragrafe
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ro">
      <body className={`${plusJakartaSans.variable} ${inter.variable} antialiased`}
      >
        {children}
        <Script defer src="https://cloud.umami.is/script.js"
        data-website-id="cffe3a05-0489-4419-95a9-33a48ab46468"
        strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
